[package]
name = "glhelper"
version = "0.1.8"
authors = ["Joseph A Mark <sjeohp@gmail.com>"]
license = "MIT"
description = "Convenience methods for opengl."
repository = "https://github.com/sjeohp/rust-glhelper.git"

[lib]
name = "glhelper"
path = "src/lib.rs"

[dependencies]
gl = "0.6.1"
